name: compile-arm64-in-docker
run-name: Compiling for ARM64 in Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64"
      - run: docker build -t hello --platform=arm64 .
      - run: docker run --platform=arm64 --rm hello
      # Should fail without the platform parameter as it will run as amd64
      - run: docker run --rm hello
