name: compile-amd64
run-name: Compiling for AMD64
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gcc -o test.o hello.c
      - run: hello.o
