name: compile-arm64-in-docker
run-name: Compiling for ARM64 in Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64"
      - run: docker build -t hello --platform=arm64 .
      - run: mkdir mountpoint
      - run: docker run -v $(pwd)/mountpoint:/mountpoint --platform=arm64 --rm hello
      # running hello out of docker should fail as the runner is amd64
      - run: ./mountpoint/hello.o
